//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public Nullable<short> SematId { get; set; }
    
        public virtual Semat Semat { get; set; }
    }
}
